### ISSUE TITLE
Coupling of psalm tone behaviour in Alleluias in P.T.

### ISSUE THREAD

**Issue by sethborders** [bbloomf/jgabc#14]
Set the current day to a Sunday in Easter

When you select "Completely Psalm toned" on either of the of the alleluias, the other gets changed too.  Was this intentional?

**Comment by bbloomf** [comment]
This was intentional because of the way the two Alleluias go together, and the way I chose to do the "completely psalm toned" to mimic the way [Rossini](http://media.musicasacra.com/pdf/rossini.pdf) did it in his psalm toned propers, but it could be improved.

When singing the full tones, the first alleluia is sung twice, followed by the verse.  Then is sung the second alleluia followed by its verse, and then a repetition of the second alleluia.

When fully psalm toning the first alleluia and its verse, it adds the text "alleluia" to the end of the first verse, because it makes more sense to sing it the close of a psalm tone, and it isn't long enough by itself to warrant an entire phrase.  However, I suppose what it should do, is only add this "alleluia" if the second alleluia is also being fully psalm toned, because that's the only time that it will be necessary there.  However, I'm not sure what the best way to approach a full-tone alleluia followed by a "completely psalm-toned" alleluia.  I suppose you would have to sing the first full-tone alleluia antiphon again before starting the second alleluia verse.

Anyway, I did realize from all this, that it should be adding "alleluia" to the text of the second alleluia verse when completely psalm toning it, and it is not doing that right now.

**Comment by sethborders** [comment]
ahh. I understand now. Still, I think it's a bit odd to do it that way when
the original chant shows the middle alleluia being associated with the
second verse. I think Rosini got away with it because he used all his own
modes.  But when you use the original modes and the mode changes on the
second verse, then the middle alleluia should go along with that to bring
the listener through the mood shift.

**Comment by bbloomf** [comment]
I agree that would be a good way to do it, but I'm not sure how to put the single alleluia at the beginning of the verse.  I did just make a change to allow the first alleluia to be completely psalm toned even if the second isn't, and then it won't add the alleluia to the end of that verse.

**Comment by sethborders** [comment]
Not sure if this is quite what you want, but there have been times where i decided the Alleluia was too hard to learn on a short notice, but i still wanted something more interesting than the complete psalm tone for the Mass.  What I ended up doing was stretching the "Alleluia" across the length of the psalm tone and then repeating the second half of the tone.

To illustrate, here are 8 Alleluias you can make from each mode of psalm tone:


![psalm-alleluia](https://cloud.githubusercontent.com/assets/6531918/13788797/9b88a52a-eab7-11e5-8d72-79313e71b379.png)

[psalm-alleluia.gabc.txt](https://github.com/bbloomf/jgabc/files/174531/psalm-alleluia.gabc.txt)

**Comment by bbloomf** [comment]
Hmmm, yes, perhaps I could add that as an additional option.  Thanks for all the quick feedback.

**Comment by bbloomf** [comment]
Also, where did you find those alleluias?  It seems to me that the alleluia tones given in the liber usualis for singing Alleluia at the Communion in Paschal Time are a bit simpler of melodies, but might also work, I think.

![image](https://cloud.githubusercontent.com/assets/923595/13814958/00fd92ce-eb5f-11e5-8df5-23666f142597.png)

**Comment by sethborders** [comment]
mine are ones i've composed myself. you'll see how i did it if you compare
my alleluia to a corresponding psalm tone

>
I didn't release the Liber Usualis already had simplified alleluias.
perhaps those might work better

**Comment by sethborders** [comment]
Another Idea could be to use the Alleluias from the Chants Abreges
http://media.musicasacra.com/pdf/chantsabreges.pdf

**Comment by bbloomf** [comment]
For now, I have added an option to use the alleluias from the Chants Abrégés.  Do you think it would be beneficial at all to have the Communion alleluias from the liber usualis as another option?  Or would that just add needless complexity?  I'm not certain myself.

**Comment by sethborders** [comment]
Thats Perfect! I think the Chants Abreges Alleluias work better than the communion ones as they were actually intended for this purpose. No need to make an option for both
You may as well just rename that dropdown option to "Chants abreges" since that name is recognizable to some

**Comment by bbloomf** [comment]
Yes, that's what I was leaning toward as well.  I didn't put "Chants Abrégés" in the dropdown because it seemed so long, but I just realized that the psalm tone used for Alleluia antiphons in Chants Abrégés is the same as what I'm using, so I just changed it to say, "à la Chants Abrégés" instead, which is plenty short enough.
