### ISSUE TITLE
Introit "Exaudi Domine... tibi" improperly rendering "Full w/ Gloria Patri"

### ISSUE THREAD

**Issue by cwrinn** [bbloomf/jgabc#25]
Goes from:
![18624413_10155196858058346_466085287_n](https://cloud.githubusercontent.com/assets/46600/26320526/b3150266-3ee8-11e7-9467-812c17cce632.png)
To:
![18644382_10155196856578346_512720673_n](https://cloud.githubusercontent.com/assets/46600/26320523/b12aab86-3ee8-11e7-9fc0-17f2e12692f9.png)
Should be:
![18644549_10155196902623346_2145597964_n](https://cloud.githubusercontent.com/assets/46600/26320555/cb66ae6e-3ee8-11e7-8435-965ff5fb18fe.png)

I'm looking for where the issue is, I'm just not that fluent with your api yet.

**Comment by bbloomf** [comment]
I think the problem is that the Introit psalm tone in Mode 1 usually has an incipit "Fa sol la", but when used with introit, the Gloria Patri starts with "Do re mi", and it simply isn't checking this.  I suppose it should compare the incipit of the Gloria Patri to the normal incipit of the psalm tone (rather than comparing the clef used in the introit with the clef of the psalm tone) and do any transposition necessary to the psalm tone based on that.
