### ISSUE TITLE
Psalm Tone Error

### ISSUE THREAD

**Issue by Nokel81** [bbloomf/jgabc#44]
Comparing what the psalm tone generator does for the Graduale on Christmas Midnight Mass and what is in the back of the Liber Brevior. There seems to be a discrepancy in where the rising nume goes. (at `spelndoribus sanctorum`)

Side note: how hard would it be to have the psalm tones be provided like the full propers are in gabc format?

Brevior: 
![image](https://user-images.githubusercontent.com/8225332/66705614-1252bc00-ecf7-11e9-9950-1a90225f0592.png)

JGABC:
![image](https://user-images.githubusercontent.com/8225332/66705618-20a0d800-ecf7-11e9-9a98-e1e399fb54e4.png)

**Comment by bbloomf** [comment]
The real issue is that it basically just guesses where to put the flex and
mediant.  You can correct it by clicking the "Show Editor" link above the
Gradual, and then moving the mediant from after "útero" to after
"sanctórum".

I don't have time to go through the Brevior and mark down where all the
flexes and mediants are, and this is what would need to be done to be able
to provide GABC for the psalm toned propers.  You can get the GABC right
now by clicking "Further PDF options" at the top right of the page and then
it will show the GABC for everything, whether psalm toned or full.

*Benjamin Bloomfield*

**Comment by Nokel81** [comment]
Okay, I totally don't expect you to mark up all the brevior for me. But thanks for the note about the further pdf options.
