### ISSUE TITLE
Gloria patri is wrong on psalm tone 5

### ISSUE THREAD

**Issue by sethborders** [bbloomf/jgabc#9]
![untitled](https://cloud.githubusercontent.com/assets/6531918/11455392/53dded42-962b-11e5-8b82-e2408c7084cb.png)

Notice it goes up on the 'ri' followed by a repeated lower note. I think its supposed to go up on the 'tu'

not sure how the tool determines which note to go up on.

**Comment by veromary** [comment]
We sing it going up on "ri" - the accented syllable. Confirmed with the Liber Usualis.

**Comment by bbloomf** [comment]
Tone 5 is a termination of 2 accents: for "et Spirítui Sancto" the last two accented syllables are "-rí-" and "San-", so Veronica is right, and "ri" is in fact the proper syllable to move up on.

I think it is simply that it is easy to pronounce Spirítui with the accent on the wrong syllable, because in the nominative and genitive, the accent is on the first syllable: Spíritus.

**Comment by sethborders** [comment]
Fair enough. I'll tell my friends that they were the ones who were wrong :P

**Comment by bbloomf** [comment]
Well, I happened to run into Paul Schultz yesterday, and he actually claimed full responsibility already. :-)
